image:
  file: .gitpod.dockerfile

tasks:
  - before: >
      source ~/.bashrc
    init: |
      echo "Wait for the installation"
      cd flutter_project
      flutter pub get
    command: >
      echo "Ready!"

ports:
  - port: 6080
vscode:
  extensions:
    - Dart-Code.flutter@3.7.9
    - Dart-Code.dart-code@3.7.9
